# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/particle_system.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/particle_system.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1bproto/particle_system.proto\"=\n\x08Particle\x12\t\n\x01x\x18\x01 \x01(\x11\x12\t\n\x01y\x18\x02 \x01(\x11\x12\x0c\n\x04size\x18\x03 \x01(\x02\x12\r\n\x05\x63olor\x18\x04 \x01(\t\")\n\x12RenderInstructions\x12\x13\n\x0b\x66rame_count\x18\x01 \x01(\x05\"4\n\x05\x46rame\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x1c\n\tparticles\x18\x02 \x03(\x0b\x32\t.Particle2@\n\x08Generate\x12\x34\n\x11GenerateParticles\x12\x13.RenderInstructions\x1a\x06.Frame\"\x00\x30\x01\x62\x06proto3'
)




_PARTICLE = _descriptor.Descriptor(
  name='Particle',
  full_name='Particle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Particle.x', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Particle.y', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='Particle.size', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='Particle.color', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=92,
)


_RENDERINSTRUCTIONS = _descriptor.Descriptor(
  name='RenderInstructions',
  full_name='RenderInstructions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_count', full_name='RenderInstructions.frame_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=135,
)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='Frame.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='particles', full_name='Frame.particles', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=189,
)

_FRAME.fields_by_name['particles'].message_type = _PARTICLE
DESCRIPTOR.message_types_by_name['Particle'] = _PARTICLE
DESCRIPTOR.message_types_by_name['RenderInstructions'] = _RENDERINSTRUCTIONS
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Particle = _reflection.GeneratedProtocolMessageType('Particle', (_message.Message,), {
  'DESCRIPTOR' : _PARTICLE,
  '__module__' : 'proto.particle_system_pb2'
  # @@protoc_insertion_point(class_scope:Particle)
  })
_sym_db.RegisterMessage(Particle)

RenderInstructions = _reflection.GeneratedProtocolMessageType('RenderInstructions', (_message.Message,), {
  'DESCRIPTOR' : _RENDERINSTRUCTIONS,
  '__module__' : 'proto.particle_system_pb2'
  # @@protoc_insertion_point(class_scope:RenderInstructions)
  })
_sym_db.RegisterMessage(RenderInstructions)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), {
  'DESCRIPTOR' : _FRAME,
  '__module__' : 'proto.particle_system_pb2'
  # @@protoc_insertion_point(class_scope:Frame)
  })
_sym_db.RegisterMessage(Frame)



_GENERATE = _descriptor.ServiceDescriptor(
  name='Generate',
  full_name='Generate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=191,
  serialized_end=255,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateParticles',
    full_name='Generate.GenerateParticles',
    index=0,
    containing_service=None,
    input_type=_RENDERINSTRUCTIONS,
    output_type=_FRAME,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GENERATE)

DESCRIPTOR.services_by_name['Generate'] = _GENERATE

# @@protoc_insertion_point(module_scope)
