# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import simulator_pb2 as simulator__pb2


class SimulatorStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTask = channel.unary_unary(
                '/Simulator/GetTask',
                request_serializer=simulator__pb2.NextTaskInformation.SerializeToString,
                response_deserializer=simulator__pb2.NextTaskInformation.FromString,
                )


class SimulatorServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=simulator__pb2.NextTaskInformation.FromString,
                    response_serializer=simulator__pb2.NextTaskInformation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Simulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Simulator(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Simulator/GetTask',
            simulator__pb2.NextTaskInformation.SerializeToString,
            simulator__pb2.NextTaskInformation.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
