# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simulator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0fsimulator.proto\"8\n\x13NextTaskInformation\x12\n\n\x02id\x18\x01 \x01(\x02\x12\x15\n\rwind_variance\x18\x02 \x01(\x02\x32\x44\n\tSimulator\x12\x37\n\x07GetTask\x12\x14.NextTaskInformation\x1a\x14.NextTaskInformation\"\x00\x62\x06proto3'
)




_NEXTTASKINFORMATION = _descriptor.Descriptor(
  name='NextTaskInformation',
  full_name='NextTaskInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='NextTaskInformation.id', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wind_variance', full_name='NextTaskInformation.wind_variance', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['NextTaskInformation'] = _NEXTTASKINFORMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NextTaskInformation = _reflection.GeneratedProtocolMessageType('NextTaskInformation', (_message.Message,), {
  'DESCRIPTOR' : _NEXTTASKINFORMATION,
  '__module__' : 'simulator_pb2'
  # @@protoc_insertion_point(class_scope:NextTaskInformation)
  })
_sym_db.RegisterMessage(NextTaskInformation)



_SIMULATOR = _descriptor.ServiceDescriptor(
  name='Simulator',
  full_name='Simulator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=77,
  serialized_end=145,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTask',
    full_name='Simulator.GetTask',
    index=0,
    containing_service=None,
    input_type=_NEXTTASKINFORMATION,
    output_type=_NEXTTASKINFORMATION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMULATOR)

DESCRIPTOR.services_by_name['Simulator'] = _SIMULATOR

# @@protoc_insertion_point(module_scope)
