# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simulator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0fsimulator.proto\"\"\n\x14NewWorkerInformation\x12\n\n\x02id\x18\x01 \x01(\x05\",\n\x12NewTaskInformation\x12\x16\n\x0eparticle_count\x18\x01 \x01(\x05\x32\x89\x01\n\tSimulator\x12\x42\n\x10InitializeWorker\x12\x15.NewWorkerInformation\x1a\x15.NewWorkerInformation\"\x00\x12\x38\n\nGetNewTask\x12\x13.NewTaskInformation\x1a\x13.NewTaskInformation\"\x00\x62\x06proto3'
)




_NEWWORKERINFORMATION = _descriptor.Descriptor(
  name='NewWorkerInformation',
  full_name='NewWorkerInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='NewWorkerInformation.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=53,
)


_NEWTASKINFORMATION = _descriptor.Descriptor(
  name='NewTaskInformation',
  full_name='NewTaskInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='particle_count', full_name='NewTaskInformation.particle_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['NewWorkerInformation'] = _NEWWORKERINFORMATION
DESCRIPTOR.message_types_by_name['NewTaskInformation'] = _NEWTASKINFORMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewWorkerInformation = _reflection.GeneratedProtocolMessageType('NewWorkerInformation', (_message.Message,), {
  'DESCRIPTOR' : _NEWWORKERINFORMATION,
  '__module__' : 'simulator_pb2'
  # @@protoc_insertion_point(class_scope:NewWorkerInformation)
  })
_sym_db.RegisterMessage(NewWorkerInformation)

NewTaskInformation = _reflection.GeneratedProtocolMessageType('NewTaskInformation', (_message.Message,), {
  'DESCRIPTOR' : _NEWTASKINFORMATION,
  '__module__' : 'simulator_pb2'
  # @@protoc_insertion_point(class_scope:NewTaskInformation)
  })
_sym_db.RegisterMessage(NewTaskInformation)



_SIMULATOR = _descriptor.ServiceDescriptor(
  name='Simulator',
  full_name='Simulator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=102,
  serialized_end=239,
  methods=[
  _descriptor.MethodDescriptor(
    name='InitializeWorker',
    full_name='Simulator.InitializeWorker',
    index=0,
    containing_service=None,
    input_type=_NEWWORKERINFORMATION,
    output_type=_NEWWORKERINFORMATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetNewTask',
    full_name='Simulator.GetNewTask',
    index=1,
    containing_service=None,
    input_type=_NEWTASKINFORMATION,
    output_type=_NEWTASKINFORMATION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMULATOR)

DESCRIPTOR.services_by_name['Simulator'] = _SIMULATOR

# @@protoc_insertion_point(module_scope)
